const productTypes ={
    ADD_NEW_PRODUCT_SUCCESS:"ADD_NEW_PRODUCT_SUCCESS",
    ADD_NEW_PRODUCT_FAILURE:"ADD_NEW_PRODUCT_FAILURE",
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
}

export default productTypes;